version: "3"
services:
  ebanksvc:
    container_name: ebanksvc
    build:
      context: ../
      dockerfile: dev/Dockerfile
    image: ebanksvc
    volumes:
      - ../services:/ebank/services
      - ../shared:/ebank/shared
      - ../pb:/ebank/pb
    env_file:
      - ./local.env
    networks:
      - ebank
    ports:
      - "8080:8080"

networks:
  ebank:
    external: true
    name: ebank
    driver: "bridge"
