name: Deploy LedgerService

on:
  push:
    branches:
      - master
    paths:
      - "services/ledger/**"
      - "pb/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ebank
  GKE_ZONE: europe-west3-a
  DEPLOYMENT_NAME: ledgersvc
  SERVICE: ledger

jobs:
  build:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate protos
        run: yarn proto

      - name: Set up GoogleCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: Get GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Build the Docker image
      - name: Build
        run: |-
          docker build -f "deployment/dockerfiles/$SERVICE.Dockerfile" \
            -t "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA"

      - name: Deploy image
        run: |-
          sed -i "s/$SERVICE:latest/$SERVICE:$GITHUB_SHA/g" deployment/$SERVICE.yml
          kubectl apply -f deployment/$SERVICE.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
